### ISSUE TITLE
Wrong link

### ISSUE THREAD

**Issue by pcav** [geometalab/HTML-Image-Map-Creator-QGIS-Plugin#20]
Plugin homepage: http://plugins.qgis.org/plugins/html_image_map_creator/ (tba.) > 404

**Comment by sfkeller** [comment]
Yes. Seems it got http://plugins.qgis.org/plugins/HTML-Image-Map-Creator/ .

Maintainer (emilsivro) and Author (geometalab) are wrong too. They should be switched!
Maintainer is geometalab and Author is emilsivro:
http://plugins.qgis.org/plugins/HTML-Image-Map-Creator/

**Comment by sfkeller** [comment]
Issue resolved. 
* Plugin homepage now is http://plugins.qgis.org/plugins/html-image-map-creator/
* Maintainer is geometalab (trusted).

**Comment by sfkeller** [comment]
Issue resolved: 
* Plugin homepage is http://plugins.qgis.org/plugins/html-image-map-creator/
* Maintainer is geometalab (trusted).
