### ISSUE TITLE
Error installing on mac

### ISSUE THREAD

**Issue by Aimonius** [geometalab/HTML-Image-Map-Creator-QGIS-Plugin#21]
Triying to install on Mac (OS X 10.11.6; Python: 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]; QGIS, 2.18.9 Las Palmas) gives an error: 
Plugin is broken. Python says:
No module named html_image_map_creator_rc

Thanks.

**Comment by kannes** [comment]
Same here on Linux. No such file exists, the only _rc I have is "html_image_map_creator_resources_rc".

**Comment by sfkeller** [comment]
Same here on Windows. 

(We're working on it. Seems broken since we "cleaned up" the repo few commits ago...)

**Comment by sfkeller** [comment]
Seems to be resolved now.... ? See http://plugins.qgis.org/plugins/html-image-map-creator/version/1.0/

**Comment by Aimonius** [comment]
Resolved here.
