### ISSUE TITLE
Show number of selected objects in main dialog and other GUI issues

### ISSUE THREAD

**Issue by emilsivro** [geometalab/HTML-Image-Map-Creator-QGIS-Plugin#6]
The number of the selected object in the visible map area in QGIS is shown in the main dialog

**Comment by sfritschi** [comment]
More small issues: Enhance several GUI text elements.

**Comment by sfkeller** [comment]
* Remove marker symbol file entry.
* Add Label offset as number.
* Add Infobox offset as number.
* Replace figure and indicate what Label, Infobox and these offsets mean.
